spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_run_community
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 80
      minimum-idle: 30
      idle-timeout: 300000
      max-lifetime: 900000
      connection-timeout: 10000


logging:
  level:
    root: INFO