spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/learn_run_community
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 80
      minimum-idle: 30
      idle-timeout: 300000
      max-lifetime: 900000
      connection-timeout: 10000
  data:
    mongodb:
      uri: ${MONGODB_URI_COMMUNITY}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

logging:
  level:
    root: INFO