spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_run_community
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 80
      minimum-idle: 30
      idle-timeout: 300000
      max-lifetime: 900000
      connection-timeout: 10000
  data:
    mongodb:
      uri: mongodb://localhost:27017/learn_run_community
  kafka:
    bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 0 #전체 설정확인
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG  # MongoTemplate 쿼리 로그 출력
    root: INFO