spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/learn_run_post
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 80
      minimum-idle: 30
      idle-timeout: 300000
      max-lifetime: 900000
      connection-timeout: 10000
  data:
    mongodb:
      uri: ${MONGODB_URI_POST}
  kafka:
    bootstrap-servers: ${EC2_HOST}:10000,${EC2_HOST}:10001,${EC2_HOST}:10002
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

logging:
  level:
    root: INFO