name: Deploy infra Service to ECR and EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Copy docker-compose-infra.yml to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_INFRA_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "docker-compose-infra.yml"
          target: "~/"

      - name: Copy docker-compose-kafka.yml to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_INFRA_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "docker-compose-kafka.yml"
          target: "~/"

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_INFRA_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" > .env
            echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
            echo "MAIL_APP_PASSWORD=${{ secrets.MAIL_APP_PASSWORD }}" >> .env
            echo "MAIL_SENDER_ADDRESS=${{ secrets.MAIL_SENDER_ADDRESS }}" >> .env
            echo "MAIL_SENDER_NAME=${{ secrets.MAIL_SENDER_NAME }}" >> .env
            echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
            echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> .env
            echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> .env
            echo "MONGODB_URI_POST=${{ secrets.MONGODB_URI_POST }}" >> .env
            echo "EC2_HOST=${{ secrets.EC2_HOST }}" >> .env
            echo "EC2_INFRA_HOST=${{ secrets.EC2_INFRA_HOST }}" >> .env
            echo "MONGODB_URI_PROFILE=${{ secrets.MONGODB_URI_PROFILE }}" >> .env
            echo "MONGODB_URI_REVIEW=${{ secrets.MONGODB_URI_REVIEW }}" >> .env
            echo "MONGODB_URI_POST_READ=${{ secrets.MONGODB_URI_POST_READ }}" >> .env
            echo "MONGODB_URI_COMMENT=${{ secrets.MONGODB_URI_COMMENT }}" >> .env
            
            docker-compose -f docker-compose-infra.yml -f docker-compose-kafka.yml down
            docker-compose -f docker-compose-infra.yml -f docker-compose-kafka.yml  up -d
            docker image prune -f
